#!/usr/bin/env python
import os
import sys

_src_dir = '%s/src/' % os.path.dirname(os.path.realpath(__file__))
_file_path = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_file_path, _src_dir))

if sys.version_info[0] == 3:
    import crawler

    crawler.main()
